# Generated by Django 2.2 on 2020-01-26 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid', message='Invalid PAN', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Gender')),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
    ]
