# Generated by Django 2.2 on 2020-01-26 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid', message='Invalid name', regex='^[A-Za-z]+(?: +[A-Za-z]+)*$')]),
        ),
    ]
