# Generated by Django 2.2 on 2020-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200126_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
