# Generated by Django 2.2 on 2020-01-26 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200126_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Invalid PAN', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
